### PR TITLE
Handle less than 3 observations in ggally_cor

### LINKED ISSUE #480: ggally_cor errors out if number of samples is less than 3 rather than returning NA
When calling ggally_cor on data sets with less than 3 samples the function errors out due cor.test.default requiring more than 2 samples. It would be better if the function would not fail hard but return NA instead since ggally_cor is also used within ggpairs which would then also fail if used in conjunction with a mapping that leads to combinations with less than 3 samples.

```r
library(GGally)
data(tips, package = "reshape")
ggally_cor(tips[1:2, ], mapping = ggplot2::aes_string(x = "total_bill", y = "tip"))

```

### PR DESCRIPTION
**Pull request by bk1n**
Fixes #480

I encountered the following error when running `ggpairs` on data with less than 3 overlapping observations between two columns. Also occurs with mappings with less than 3 observations per aesthetic.
```
Error in cor.test.default(x, y, method = method, use = use) : 
  not enough finite observations
```
I thought the default behaviour should probably be to handle these by producing NA, or similar, and print a warning, so I implemented in this in `ggally_cor()`

### CODE REVIEW

File: R/gg-plots.R [hunk 1]
```diff
@@ -347,18 +347,23 @@ ggally_cor <- function(
...
+        cor_est <- as.numeric(corObj$estimate)
+        cor_txt <- formatC(cor_est, digits = digits, format = "f")
+
+        # if stars should be added
+        if (isTRUE(stars)) {
+          cor_txt <- str_c(
+            cor_txt,
+            signif_stars(corObj$p.value)
+          )
+        }
```
Comment (schloerke) [inline R/gg-plots.R:366]: Taking the approach from https://github.com/ggobi/ggally/pull/513/files#diff-7af1e69ba80a0f5423ab07b42e989a8bd7c2e79575c9f8e54244bb17a2a2a075R352

```suggestion
      if (length(x) < 3 | length(y) < 3) {
        warning("Less than 2 observations, returning NA")
        return("NA")
      }

      corObj <- stats::cor.test(x, y, method = method, use = use)

      # make sure all values have X-many decimal places
      cor_est <- as.numeric(corObj$estimate)
      cor_txt <- formatC(cor_est, digits = digits, format = "f")

      # if stars should be added
      if (isTRUE(stars)) {
        cor_txt <- str_c(
          cor_txt,
          signif_stars(corObj$p.value)
        )
```

**Comment by schloerke** [comment]
Thank you, @bk1n !
